/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.finalproject.druglifecycle;

import com.finalproject.backend.Employee;
import com.finalproject.backend.EmployeeDirectory;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author tarush
 */
public class drugLifeCycle extends javax.swing.JFrame {

    /**
     * Creates new form drugLifeCycle
     */
    
    public static String gender;
    EmployeeDirectory empDir = new EmployeeDirectory();

    public drugLifeCycle() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        passwordField1 = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        Registration = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        nameLabelR = new javax.swing.JLabel();
        ageLabelR = new javax.swing.JLabel();
        genderLabelR = new javax.swing.JLabel();
        dobLabelR = new javax.swing.JLabel();
        numberLabelR = new javax.swing.JLabel();
        mailIDLabelR = new javax.swing.JLabel();
        addressLabelR = new javax.swing.JLabel();
        zipCodeLabelR = new javax.swing.JLabel();
        firstnameTextField1 = new javax.swing.JTextField();
        middlenameTextField1 = new javax.swing.JTextField();
        lastnameTextField1 = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        DateofBirthChooser1 = new com.toedter.calendar.JDateChooser();
        maleRadioButton1 = new javax.swing.JRadioButton();
        femaleRadioButton1 = new javax.swing.JRadioButton();
        othersRadioButton1 = new javax.swing.JRadioButton();
        numberTextField1 = new javax.swing.JTextField();
        emailIDTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea1 = new javax.swing.JTextArea();
        zipcodeTextField1 = new javax.swing.JTextField();
        organizationLabelR = new javax.swing.JLabel();
        organizationComboBoxR = new javax.swing.JComboBox<>();
        roleLabelR = new javax.swing.JLabel();
        usernameLabelR = new javax.swing.JLabel();
        usernameTextFieldR = new javax.swing.JTextField();
        passwordLabelR = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        roleComboBoxR = new javax.swing.JComboBox<>();
        cancelButtonR = new javax.swing.JButton();
        submitButtonR = new javax.swing.JButton();
        enterpriseLabelR = new javax.swing.JLabel();
        enterpriseComboBoxR = new javax.swing.JComboBox<>();
        Workspace = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        rightComponent = new javax.swing.JPanel();
        logoutButton1 = new javax.swing.JButton();
        leftComponent = new javax.swing.JPanel();
        firstLoginEnterprise = new javax.swing.JPanel();
        firstLoginEnterpriseTitle = new javax.swing.JLabel();
        firstLoginEnterpriseName = new javax.swing.JLabel();
        firstLoginEnterpriseNameTextField = new javax.swing.JTextField();
        firstLoginEnterpriseType = new javax.swing.JLabel();
        firstLoginEnterpriseTypeComboBox = new javax.swing.JComboBox<>();
        addEnterpriseButton = new javax.swing.JButton();
        firstLoginEnterpriseMyRoleLabel = new javax.swing.JLabel();
        firstLoginEnterpriseMyRoleTextField = new javax.swing.JTextField();
        firstLoginEnterpriseMyOrganizationLabel = new javax.swing.JLabel();
        firstLoginEnterpriseMyOrganizationTextField = new javax.swing.JTextField();
        firstLoginOrganization = new javax.swing.JPanel();
        firstLoginOrganizationTitleLabel = new javax.swing.JLabel();
        firsLognOrganzationNameLabel = new javax.swing.JLabel();
        firstLoginOrganizationNameTextField = new javax.swing.JTextField();
        firstLoginOrganizationAddButton = new javax.swing.JButton();
        firstLoginOrganizationRoleTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parent.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Application");

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerButton))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLabel)
                                    .addComponent(usernameLabel))
                                .addGap(33, 33, 33)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTextField1)
                                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(registerButton))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        Parent.add(Login, "card2");

        Registration.setBackground(new java.awt.Color(255, 255, 255));

        Title.setText("Registration");

        nameLabelR.setText("Name:");

        ageLabelR.setText("Age:");

        genderLabelR.setText("Gender:");

        dobLabelR.setText("Date of birth:");

        numberLabelR.setText("Contact No.:");

        mailIDLabelR.setText("Email ID:");

        addressLabelR.setText("Address:");

        zipCodeLabelR.setText("Zip Code:");

        firstnameTextField1.setText("First name");

        middlenameTextField1.setText("Middle name");

        lastnameTextField1.setText("Last name");

        maleRadioButton1.setText("Male");
        maleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButton1ActionPerformed(evt);
            }
        });

        femaleRadioButton1.setText("Female");
        femaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButton1ActionPerformed(evt);
            }
        });

        othersRadioButton1.setText("Others");
        othersRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersRadioButton1ActionPerformed(evt);
            }
        });

        numberTextField1.setText("1234567890");
        numberTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextField1ActionPerformed(evt);
            }
        });

        emailIDTextField1.setText("abc@gmail.com");

        addressTextArea1.setColumns(20);
        addressTextArea1.setRows(5);
        jScrollPane1.setViewportView(addressTextArea1);

        zipcodeTextField1.setText("00000");

        organizationLabelR.setText("Organization:");

        organizationComboBoxR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New organization" }));
        organizationComboBoxR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationComboBoxRActionPerformed(evt);
            }
        });

        roleLabelR.setText("Role:");

        usernameLabelR.setText("Username:");

        usernameTextFieldR.setText("Username");

        passwordLabelR.setText("Password:");

        roleComboBoxR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New role" }));

        cancelButtonR.setText("Cancel");
        cancelButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonRActionPerformed(evt);
            }
        });

        submitButtonR.setText("Submit");
        submitButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonRActionPerformed(evt);
            }
        });

        enterpriseLabelR.setText("Enterprise:");

        enterpriseComboBoxR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New enterprise" }));
        enterpriseComboBoxR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseComboBoxRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistrationLayout = new javax.swing.GroupLayout(Registration);
        Registration.setLayout(RegistrationLayout);
        RegistrationLayout.setHorizontalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(Title)
                .addGap(207, 207, 207))
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationLayout.createSequentialGroup()
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberLabelR, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(addressLabelR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zipCodeLabelR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zipcodeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addComponent(numberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mailIDLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(271, 271, 271))
                    .addGroup(RegistrationLayout.createSequentialGroup()
                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationLayout.createSequentialGroup()
                                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(usernameLabelR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addComponent(ageLabelR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameLabelR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(genderLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationLayout.createSequentialGroup()
                                        .addComponent(maleRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(femaleRadioButton1)
                                        .addGap(9, 9, 9)
                                        .addComponent(othersRadioButton1))
                                    .addGroup(RegistrationLayout.createSequentialGroup()
                                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernameTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(RegistrationLayout.createSequentialGroup()
                                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(dobLabelR)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(RegistrationLayout.createSequentialGroup()
                                                .addComponent(passwordLabelR)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(DateofBirthChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(RegistrationLayout.createSequentialGroup()
                                        .addComponent(firstnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(middlenameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegistrationLayout.createSequentialGroup()
                                    .addComponent(enterpriseLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(enterpriseComboBoxR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(RegistrationLayout.createSequentialGroup()
                                    .addComponent(roleLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(roleComboBoxR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(RegistrationLayout.createSequentialGroup()
                                    .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(organizationLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelButtonR))
                                    .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RegistrationLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(submitButtonR))
                                        .addGroup(RegistrationLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(organizationComboBoxR, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        RegistrationLayout.setVerticalGroup(
            RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelR)
                    .addComponent(firstnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middlenameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageLabelR)
                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dobLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DateofBirthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabelR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameLabelR)
                        .addComponent(usernameTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabelR)
                    .addComponent(maleRadioButton1)
                    .addComponent(femaleRadioButton1)
                    .addComponent(othersRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailIDLabelR)
                    .addComponent(numberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabelR)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcodeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabelR)
                    .addComponent(enterpriseComboBoxR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationComboBoxR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleLabelR)
                    .addComponent(roleComboBoxR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(RegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtonR)
                    .addComponent(submitButtonR))
                .addGap(52, 52, 52))
        );

        Parent.add(Registration, "card3");

        rightComponent.setBackground(new java.awt.Color(51, 51, 51));
        rightComponent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rightComponent.setAlignmentY(0.8F);

        logoutButton1.setText("Logout");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightComponentLayout = new javax.swing.GroupLayout(rightComponent);
        rightComponent.setLayout(rightComponentLayout);
        rightComponentLayout.setHorizontalGroup(
            rightComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightComponentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        rightComponentLayout.setVerticalGroup(
            rightComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightComponentLayout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(logoutButton1)
                .addGap(20, 20, 20))
        );

        jSplitPane1.setLeftComponent(rightComponent);

        leftComponent.setBackground(new java.awt.Color(255, 255, 255));
        leftComponent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        leftComponent.setAlignmentY(0.8F);
        leftComponent.setLayout(new java.awt.CardLayout());

        firstLoginEnterprise.setBackground(new java.awt.Color(255, 255, 255));

        firstLoginEnterpriseTitle.setBackground(new java.awt.Color(0, 0, 0));
        firstLoginEnterpriseTitle.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        firstLoginEnterpriseTitle.setText("Welcome to Enterprise creation");

        firstLoginEnterpriseName.setText("Enterprise name:");

        firstLoginEnterpriseNameTextField.setToolTipText("");

        firstLoginEnterpriseType.setText("Enterprise type:");

        firstLoginEnterpriseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "Research institute", "Mass manufacturers", "Chemical suppliers", "Pre/Post clinical trials handling", "Food and drug administration" }));

        addEnterpriseButton.setText("Add enterprise");
        addEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseButtonActionPerformed(evt);
            }
        });

        firstLoginEnterpriseMyRoleLabel.setText("My Role:");

        firstLoginEnterpriseMyOrganizationLabel.setText("Organization:");

        javax.swing.GroupLayout firstLoginEnterpriseLayout = new javax.swing.GroupLayout(firstLoginEnterprise);
        firstLoginEnterprise.setLayout(firstLoginEnterpriseLayout);
        firstLoginEnterpriseLayout.setHorizontalGroup(
            firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstLoginEnterpriseLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstLoginEnterpriseTitle)
                    .addGroup(firstLoginEnterpriseLayout.createSequentialGroup()
                        .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstLoginEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(firstLoginEnterpriseName))
                            .addComponent(firstLoginEnterpriseMyRoleLabel)
                            .addComponent(firstLoginEnterpriseMyOrganizationLabel))
                        .addGap(18, 18, 18)
                        .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addEnterpriseButton)
                            .addComponent(firstLoginEnterpriseNameTextField)
                            .addComponent(firstLoginEnterpriseTypeComboBox, 0, 200, Short.MAX_VALUE)
                            .addComponent(firstLoginEnterpriseMyRoleTextField)
                            .addComponent(firstLoginEnterpriseMyOrganizationTextField))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        firstLoginEnterpriseLayout.setVerticalGroup(
            firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstLoginEnterpriseLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(firstLoginEnterpriseTitle)
                .addGap(34, 34, 34)
                .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLoginEnterpriseName)
                    .addComponent(firstLoginEnterpriseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLoginEnterpriseType)
                    .addComponent(firstLoginEnterpriseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLoginEnterpriseMyRoleLabel)
                    .addComponent(firstLoginEnterpriseMyRoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstLoginEnterpriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLoginEnterpriseMyOrganizationLabel)
                    .addComponent(firstLoginEnterpriseMyOrganizationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEnterpriseButton)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        leftComponent.add(firstLoginEnterprise, "card2");

        firstLoginOrganization.setBackground(new java.awt.Color(255, 255, 255));

        firstLoginOrganizationTitleLabel.setText("Welcome");

        firsLognOrganzationNameLabel.setText("Organization name:");
        firsLognOrganzationNameLabel.setToolTipText("");

        firstLoginOrganizationAddButton.setText("Add");
        firstLoginOrganizationAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstLoginOrganizationAddButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("My Role:");

        javax.swing.GroupLayout firstLoginOrganizationLayout = new javax.swing.GroupLayout(firstLoginOrganization);
        firstLoginOrganization.setLayout(firstLoginOrganizationLayout);
        firstLoginOrganizationLayout.setHorizontalGroup(
            firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstLoginOrganizationLayout.createSequentialGroup()
                .addGroup(firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstLoginOrganizationLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(firstLoginOrganizationTitleLabel))
                    .addGroup(firstLoginOrganizationLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firsLognOrganzationNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstLoginOrganizationAddButton)
                            .addComponent(firstLoginOrganizationNameTextField)
                            .addComponent(firstLoginOrganizationRoleTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        firstLoginOrganizationLayout.setVerticalGroup(
            firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstLoginOrganizationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(firstLoginOrganizationTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firsLognOrganzationNameLabel)
                    .addComponent(firstLoginOrganizationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstLoginOrganizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(firstLoginOrganizationLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(firstLoginOrganizationRoleTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(firstLoginOrganizationAddButton)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        leftComponent.add(firstLoginOrganization, "card3");

        jSplitPane1.setRightComponent(leftComponent);

        javax.swing.GroupLayout WorkspaceLayout = new javax.swing.GroupLayout(Workspace);
        Workspace.setLayout(WorkspaceLayout);
        WorkspaceLayout.setHorizontalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        WorkspaceLayout.setVerticalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        Parent.add(Workspace, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    public void PanelPaint(JPanel page){
        Parent.removeAll();
        Parent.add(page);
        Parent.repaint();
        Parent.revalidate();
    }
    
    public String resRepIDGen(){
        Random ran = new Random();
        int idInt = ran.nextInt(100);
        String encID = "RER-"+idInt;
        return encID;
    }
    
    public void SplitPanelPain(JPanel page){
        leftComponent.removeAll();
        leftComponent.add(page);
        leftComponent.repaint();
        leftComponent.revalidate();
    }
    
    public void SplitPanelPainReports(JTabbedPane page){
        leftComponent.removeAll();
        leftComponent.add(page);
        leftComponent.repaint();
        leftComponent.revalidate();
    }
    
        public void disableDropdownOrganization(){
        if(enterpriseComboBoxR.getSelectedItem().toString().equals("New enterprise")){
            organizationComboBoxR.setEnabled(false);
        }else{
            organizationComboBoxR.setEnabled(true);
        }
    }
    
    public void disableDropdownRole(){
        if (organizationComboBoxR.getSelectedItem().toString().equals("New organization")){
            roleComboBoxR.setEnabled(false);
        }else{
            roleComboBoxR.setEnabled(true);
        }
    }
    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        PanelPaint(Workspace);
        Employee empWorkSpace = empDir.sendParticularUser(usernameTextField1.getText(), String.valueOf(passwordField1.getPassword()));
        if (empWorkSpace.getEnterpriseName().toString().equals("New enterprise")){
            SplitPanelPain(firstLoginEnterprise);
        }else if (empWorkSpace.getOrganizationName().toString().equals("New organization")){
            SplitPanelPain(firstLoginOrganization);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        PanelPaint(Registration);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void maleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButton1ActionPerformed
        gender = "Male";
    }//GEN-LAST:event_maleRadioButton1ActionPerformed

    private void femaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButton1ActionPerformed
        gender = "Female";
    }//GEN-LAST:event_femaleRadioButton1ActionPerformed

    private void othersRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersRadioButton1ActionPerformed
        gender = "Others";
    }//GEN-LAST:event_othersRadioButton1ActionPerformed

    private void numberTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextField1ActionPerformed

    private void organizationComboBoxRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationComboBoxRActionPerformed
        disableDropdownRole();
    }//GEN-LAST:event_organizationComboBoxRActionPerformed

    private void cancelButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonRActionPerformed
        PanelPaint(Login);
    }//GEN-LAST:event_cancelButtonRActionPerformed

    private void submitButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonRActionPerformed
        Employee emp = empDir.addEmployee();
        String name = firstnameTextField1.getText() + " "+middlenameTextField1.getText() + " "+lastnameTextField1.getText();
        emp.setName(name);
        emp.setAge(Integer.valueOf(ageTextField.getText()));
        emp.setDateofBirth(DateofBirthChooser1.getDate());
        emp.setUsername(usernameTextFieldR.getText());
        emp.setPassword(String.valueOf(jPasswordField1.getPassword()));
        emp.setGender(gender);
        emp.setPhoneNumber(Integer.valueOf(numberTextField1.getText()));
        emp.setMailID(emailIDTextField1.getText());
        emp.setAddress(addressTextArea1.getText());
        emp.setZipcode(Integer.valueOf(zipcodeTextField1.getText()));
        emp.setEnterpriseName(enterpriseComboBoxR.getSelectedItem().toString());
        emp.setOrganizationName(organizationComboBoxR.getSelectedItem().toString());
        emp.setRole(roleComboBoxR.getSelectedItem().toString());
        System.out.println(roleComboBoxR.getSelectedItem().toString());
        PanelPaint(Login);
    }//GEN-LAST:event_submitButtonRActionPerformed

    private void enterpriseComboBoxRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseComboBoxRActionPerformed
        disableDropdownOrganization();
    }//GEN-LAST:event_enterpriseComboBoxRActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        PanelPaint(Login);
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void addEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseButtonActionPerformed
        Employee loggedINEmployee = empDir.sendParticularUser(usernameTextField1.getText(), String.valueOf(passwordField1.getPassword()));
        loggedINEmployee.setEnterpriseName(firstLoginEnterpriseNameTextField.getText());
        loggedINEmployee.setEnterpriseType(firstLoginEnterpriseTypeComboBox.getSelectedItem().toString());
        loggedINEmployee.setRole(firstLoginEnterpriseMyRoleTextField.getText());
        loggedINEmployee.setOrganizationName(firstLoginEnterpriseMyOrganizationTextField.getText());
        JOptionPane.showMessageDialog(this, "Enterprise created. Please re-login.");
        enterpriseComboBoxR.addItem(firstLoginEnterpriseNameTextField.getText());
        organizationComboBoxR.addItem(firstLoginEnterpriseMyOrganizationTextField.getText());
    }//GEN-LAST:event_addEnterpriseButtonActionPerformed

    private void firstLoginOrganizationAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstLoginOrganizationAddButtonActionPerformed
        Employee loggedINEmployee = empDir.sendParticularUser(usernameTextField1.getText(), String.valueOf(passwordField1.getPassword()));
        loggedINEmployee.setOrganizationName(firstLoginOrganizationNameTextField.getText());
        loggedINEmployee.setRole(firstLoginOrganizationRoleTextField1.getText());
        organizationComboBoxR.addItem(firstLoginOrganizationNameTextField.getText());
        roleComboBoxR.addItem(firstLoginOrganizationRoleTextField1.getText());
    }//GEN-LAST:event_firstLoginOrganizationAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drugLifeCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drugLifeCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drugLifeCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drugLifeCycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drugLifeCycle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateofBirthChooser1;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel Registration;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Workspace;
    private javax.swing.JButton addEnterpriseButton;
    private javax.swing.JLabel addressLabelR;
    private javax.swing.JTextArea addressTextArea1;
    private javax.swing.JLabel ageLabelR;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton cancelButtonR;
    private javax.swing.JLabel dobLabelR;
    private javax.swing.JTextField emailIDTextField1;
    private javax.swing.JComboBox<String> enterpriseComboBoxR;
    private javax.swing.JLabel enterpriseLabelR;
    private javax.swing.JRadioButton femaleRadioButton1;
    private javax.swing.JLabel firsLognOrganzationNameLabel;
    private javax.swing.JPanel firstLoginEnterprise;
    private javax.swing.JLabel firstLoginEnterpriseMyOrganizationLabel;
    private javax.swing.JTextField firstLoginEnterpriseMyOrganizationTextField;
    private javax.swing.JLabel firstLoginEnterpriseMyRoleLabel;
    private javax.swing.JTextField firstLoginEnterpriseMyRoleTextField;
    private javax.swing.JLabel firstLoginEnterpriseName;
    private javax.swing.JTextField firstLoginEnterpriseNameTextField;
    private javax.swing.JLabel firstLoginEnterpriseTitle;
    private javax.swing.JLabel firstLoginEnterpriseType;
    private javax.swing.JComboBox<String> firstLoginEnterpriseTypeComboBox;
    private javax.swing.JPanel firstLoginOrganization;
    private javax.swing.JButton firstLoginOrganizationAddButton;
    private javax.swing.JTextField firstLoginOrganizationNameTextField;
    private javax.swing.JTextField firstLoginOrganizationRoleTextField1;
    private javax.swing.JLabel firstLoginOrganizationTitleLabel;
    private javax.swing.JTextField firstnameTextField1;
    private javax.swing.JLabel genderLabelR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lastnameTextField1;
    private javax.swing.JPanel leftComponent;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JLabel mailIDLabelR;
    private javax.swing.JRadioButton maleRadioButton1;
    private javax.swing.JTextField middlenameTextField1;
    private javax.swing.JLabel nameLabelR;
    private javax.swing.JLabel numberLabelR;
    private javax.swing.JTextField numberTextField1;
    private javax.swing.JComboBox<String> organizationComboBoxR;
    private javax.swing.JLabel organizationLabelR;
    private javax.swing.JRadioButton othersRadioButton1;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabelR;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel rightComponent;
    private javax.swing.JComboBox<String> roleComboBoxR;
    private javax.swing.JLabel roleLabelR;
    private javax.swing.JButton submitButtonR;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabelR;
    private javax.swing.JTextField usernameTextField1;
    private javax.swing.JTextField usernameTextFieldR;
    private javax.swing.JLabel zipCodeLabelR;
    private javax.swing.JTextField zipcodeTextField1;
    // End of variables declaration//GEN-END:variables
}
